# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-21 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_user', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Vpx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('servicetype', models.CharField(max_length=100)),
                ('curstate', models.CharField(max_length=100)),
                ('effectivestate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('lbmethod', models.CharField(max_length=100)),
                ('backuplbmethod', models.CharField(max_length=100)),
                ('health', models.CharField(max_length=100)),
                ('totalservices', models.CharField(max_length=100)),
                ('activeservices', models.CharField(max_length=100)),
                ('statechangetimesec', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacci\xf3n')),
            ],
        ),
    ]
